# Generated by Django 4.1.1 on 2022-09-17 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dep_description',
            new_name='dep_decription',
        ),
    ]
